# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: xlasa-ol <xlasa-ol@student.42urduliz.com   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/08/03 11:45:26 by xlasa-ol          #+#    #+#              #
#    Updated: 2021/08/15 15:43:42 by xlasa-ol         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME    = libft.a

SRCS    = ft_atoi.c\
          ft_bzero.c\
          ft_calloc.c\
          ft_isalnum.c\
          ft_isalpha.c\
          ft_isascii.c\
          ft_isdigit.c\
          ft_isprint.c\
          ft_memchr.c\
          ft_memcmp.c\
          ft_memcpy.c\
          ft_memmove.c\
          ft_memset.c\
          ft_strlcat.c\
          ft_strchr.c\
          ft_strlcpy.c\
          ft_strdup.c\
          ft_strlen.c\
          ft_strncmp.c\
          ft_strnstr.c\
          ft_strrchr.c\
          ft_tolower.c\
          ft_toupper.c\
          ft_itoa.c\
          ft_putchar_fd.c\
          ft_putendl_fd.c\
          ft_putnbr_fd.c\
          ft_putstr_fd.c\
          ft_split.c\
          ft_strjoin.c\
          ft_strtrim.c\
          ft_substr.c\
          ft_strmapi.c\
          ft_striteri.c\

OBJS	= $(SRCS:.c=.o)

BONUS	 = ft_lstadd_front.c\
		  ft_lstlast.c\
		  ft_lstnew.c\
		  ft_lstsize.c\
		  ft_lstadd_back.c\
		  ft_striteri.c\
		  ft_lstclear.c\
		  ft_lstdelone.c\
		  ft_lstiter.c\
		  ft_lstmap.c\

BONUS_OBJS = $(BONUS:.c=.o)

LIBC	= ar rcs

CC      = gcc

RM      = rm -f

CFLAGS  = -Wall -Wextra -Werror

INCS    = libft.h

$(NAME): $(OBJS) $(INCS)
	$(LIBC) $(NAME) $(OBJS)

all:    $(NAME)

bonus:	$(OBJS) $(BONUS_OBJS) $(INCS)
	$(LIBC) $(NAME) $(OBJS) $(BONUS_OBJS)

clean:
	$(RM) $(OBJS) $(BONUS_OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all bonus clean fclean re .c .o
